# Generated by Django 5.1.5 on 2025-03-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LPProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "objective_type",
                    models.CharField(
                        choices=[("MAX", "Maximize"), ("MIN", "Minimize")], max_length=3
                    ),
                ),
                (
                    "objective_function",
                    models.JSONField(help_text="Coefficients of objective function"),
                ),
                (
                    "constraints_lhs",
                    models.JSONField(
                        help_text="Left-hand side coefficients of constraints"
                    ),
                ),
                (
                    "constraints_rhs",
                    models.JSONField(help_text="Right-hand side values of constraints"),
                ),
                (
                    "constraints_signs",
                    models.JSONField(help_text="Signs of constraints (≤, ≥, =)"),
                ),
                ("num_variables", models.IntegerField()),
                ("num_constraints", models.IntegerField()),
                ("solution", models.JSONField(blank=True, null=True)),
                ("is_solved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Linear Programming Problem",
                "verbose_name_plural": "Linear Programming Problems",
            },
        ),
        migrations.CreateModel(
            name="TransportationProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("supply", models.JSONField(help_text="Supply values from sources")),
                ("demand", models.JSONField(help_text="Demand values at destinations")),
                (
                    "cost_matrix",
                    models.JSONField(help_text="Transportation costs matrix"),
                ),
                ("num_sources", models.IntegerField()),
                ("num_destinations", models.IntegerField()),
                ("solution", models.JSONField(blank=True, null=True)),
                ("total_cost", models.FloatField(blank=True, null=True)),
                ("is_solved", models.BooleanField(default=False)),
                (
                    "method_used",
                    models.CharField(
                        choices=[
                            ("NWCR", "Northwest Corner Rule"),
                            ("LCM", "Least Cost Method"),
                            ("VAM", "Vogel's Approximation"),
                        ],
                        default="NWCR",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportation Problem",
                "verbose_name_plural": "Transportation Problems",
            },
        ),
    ]
