# Generated by Django 5.1.5 on 2025-03-03 02:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_number", models.CharField(max_length=10, unique=True)),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("ICU", "Intensive Care Unit"),
                            ("GEN", "General Ward"),
                            ("EMR", "Emergency"),
                            ("PED", "Pediatric"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                ("floor", models.PositiveIntegerField()),
                ("ward", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("equipment_type", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("maintenance_due", models.DateField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("current_location", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("max_patients", models.PositiveIntegerField(default=10)),
                ("current_patients", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("admission_date", models.DateTimeField(auto_now_add=True)),
                ("diagnosis", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ADM", "Admitted"),
                            ("DIS", "Discharged"),
                            ("WAI", "Waiting"),
                            ("TRE", "Under Treatment"),
                        ],
                        default="WAI",
                        max_length=3,
                    ),
                ),
                ("expected_stay_days", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_bed",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.bed",
                    ),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.doctor",
                    ),
                ),
                (
                    "required_equipment",
                    models.ManyToManyField(blank=True, to="hospital.equipment"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateTimeField(auto_now_add=True)),
                ("expected_end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("priority_score", models.FloatField(default=0.0)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hospital.bed"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority_score", "-assignment_date"],
            },
        ),
    ]
