# Generated by Django 5.1.5 on 2025-03-03 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={},
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="assignment_date",
            new_name="assigned_date",
        ),
        migrations.RenameField(
            model_name="bed",
            old_name="bed_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="specialization",
            new_name="specialty",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="diagnosis",
            new_name="condition",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="expected_end_date",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="priority_score",
        ),
        migrations.RemoveField(
            model_name="bed",
            name="bed_type",
        ),
        migrations.RemoveField(
            model_name="bed",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="current_patients",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="current_location",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="maintenance_due",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="assigned_bed",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="assigned_doctor",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="expected_stay_days",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="gender",
        ),
        migrations.AddField(
            model_name="assignment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="last_maintenance",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintenance_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="next_maintenance",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("AV", "Available"),
                    ("UM", "Under Maintenance"),
                    ("NA", "Not Available"),
                ],
                default="AV",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="max_patients",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("MON", "Monitoring Equipment"),
                    ("DIA", "Diagnostic Equipment"),
                    ("THE", "Therapeutic Equipment"),
                    ("LIF", "Life Support Equipment"),
                    ("OTH", "Other"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                    (5, "Emergency"),
                ],
                default=1,
            ),
        ),
        migrations.RemoveField(
            model_name="patient",
            name="required_equipment",
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAI", "Waiting"),
                    ("ADM", "Admitted"),
                    ("TRE", "Under Treatment"),
                    ("DIS", "Discharged"),
                ],
                default="WAI",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="required_equipment",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
