# Generated by Django 5.1.5 on 2025-03-03 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="diagnosis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="expected_stay_days",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
