# Generated by Django 5.1.6 on 2025-04-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_patient_diagnosis_patient_expected_stay_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="assigned_bed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.bed",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.doctor",
            ),
        ),
    ]
